security:
    encoders:
        App\Entity\Users:
            algorithm: auto

    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
          lazy: true
          guard:
              authenticators:
                  - App\Security\LoginAuthenticator
          logout:
            path: app_logout

    access_control:
        - { path: '/admin', roles: ROLE_ADMIN }
        - { path: '/director', roles: ROLE_DIRECTOR}
        - { path: '/teacher', roles: ROLE_TEACHER }
        - { path: '/student', roles: ROLE_STUDENT }
#        - { path: '/homepage', roles: IS_AUTHENTICATED_ANONYMOUSLY }
